Alan/ember v2
Schulich-Ignite/ember-bot pull request #4
Opened 2021-02-08 00:38 UTC by AlanAyy

2021-02-08 01:00 UTC, AlphaRLee requested changes
Waiting on fix to permissions & README.md file. The rest of the changes from PR #2 are lower priorities

2021-02-08 01:23 UTC, AlanAyy commented on cogs/admin.py
> +            if group == channel.name and group not in ['Exec', 'President', 'Mentor']:
Fixed.
It won't give a role that doesn't match a channel name letter-for-letter, so as long as there's no channel with exactly the same name as a role AND it doesn't match any names of most of the high-importance roles (included for extra safety), it won't happen.

2021-02-08 02:15 UTC, AlphaRLee reviewed
Looks good to me. Going to wait to see if @raduschirliu has any comments before approving

2021-02-08 02:33 UTC, raduschirliu submitted a review, later dismissed

2021-02-08 02:33 UTC, raduschirliu commented on cogs/admin.py
> +                    group.lower() not in ['exec', 'president', 'mentor', 'lecture lead', 'jr exec']):
Maybe make the list of banned roles a constant variable somewhere, or load from config?

2021-02-08 02:35 UTC, raduschirliu commented on cogs/admin.py
> +                    group.lower() not in ['exec', 'president', 'mentor', 'lecture lead', 'jr exec']):
Or perhaps another option, although may be a bit more work - rather than having a list of banned roles, it may be safer to have a list of *allowed* roles instead.

Could do something along the line so: every time we create a new channel/role combo, add that role to our config under "allowed roles", and only those roles should then be usable.

2021-02-08 03:50 UTC, AlanAyy commented on cogs/admin.py
> +                    group.lower() not in ['exec', 'president', 'mentor', 'lecture lead', 'jr exec']):
Oof, it's doable but it'll take me another couple of hours to add that in... I'll see what I can do

2021-02-08 05:27 UTC, raduschirliu commented on cogs/admin.py
> +                    group.lower() not in ['exec', 'president', 'mentor', 'lecture lead', 'jr exec']):
Yeah, I figured it may be way too much work. If it seems like it, then we could just leave it this way for now and be careful to include all the roles, and do that for the next version :)))

2021-02-08 20:43 UTC, AlanAyy commented on cogs/admin.py
> +                    group.lower() not in ['exec', 'president', 'mentor', 'lecture lead', 'jr exec']):
I think that's the play... I'm a little behind on some assignments but over the break I'll have lots of time to have a proper .json remembering all the channels it's made (like a whitelist of roles it can give out)

2021-02-15 18:36 UTC, AlphaRLee approved these changes

2021-02-15 18:37 UTC, AlphaRLee commented
Looks good to me, feel free to merge

2021-02-16 00:27 UTC, merged